version: "2"
services:
  node:
    image: "node:12"
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: >
      sh -c "npm i && npm start"